language: node_js
node_js:
- "6.4.0"

before_script:
    - sudo ln -s $(which node) /bin

script:
    - npm test
    - npm run-script coverage

after_script:
    - codeclimate-test-reporter < ./coverage/lcov.info

after_success:
    - bash ./deploy.sh

